import re

# --- UI & Style Constants ---
LINGUISTIC_STYLES = [
    "auto", "casual", "charming", "direct", "intellectual", "mysterious",
    "playful", "poetic", "sarcastic", "sexual", "witty"
]
HUMOR_STYLES = ["none", "witty", "sarcastic", "goofy", "dry", "self-deprecating"]
EMOJI_STRATEGIES = ["auto", "none", "sparing", "heavy"]
DATE_ARC_PHASES = ["rapport", "escalation", "planning", "post_date"]
STRATEGY_MODES = ["Patient", "Balanced", "Aggressive"]

# --- Word & Phrase Dictionaries for Analysis ---

# Sentiment & Arousal
POSITIVE_WORDS = {
    "love": 0.9, "amazing": 0.9, "incredible": 0.9, "perfect": 0.95, "gorgeous": 0.9,
    "beautiful": 0.85, "awesome": 0.8, "brilliant": 0.8, "fantastic": 0.8, "wonderful": 0.8,
    "absolutely": 0.7, "definitely": 0.7, "happy": 0.7, "excited": 0.7, "hilarious": 0.7,
    "lovely": 0.7, "great": 0.7, "fun": 0.6, "sweet": 0.6, "dope": 0.6, "cute": 0.6,
    "interesting": 0.5, "nice": 0.5, "cool": 0.4, "totally": 0.6, "wow": 0.7, "acceptable": 0.2,
    "adequate": 0.1, "agreeable": 0.4, "alright": 0.3, "appealing": 0.5, "appreciated": 0.5,
    "approved": 0.4, "charming": 0.5, "comfy": 0.4, "decent": 0.4, "enjoyable": 0.5,
    "favorable": 0.4, "fine": 0.3, "good": 0.5, "helpful": 0.5, "okay": 0.2, "pleasant": 0.5,
    "pleasing": 0.5, "satisfactory": 0.3, "solid": 0.5, "sound": 0.4, "sufficient": 0.2,
    "welcome": 0.5, "accomplished": 0.8, "admirable": 0.7, "adorable": 0.7, "astounding": 0.8,
    "breathtaking": 0.8, "captivating": 0.7, "classic": 0.7, "compelling": 0.7, "dazzling": 0.8,
    "delightful": 0.7, "divine": 0.8, "dynamic": 0.7, "effective": 0.6, "efficient": 0.6,
    "elegant": 0.7, "enchanting": 0.8, "engaging": 0.7, "exceptional": 0.8, "fabulous": 0.8,
    "impressive": 0.8, "legendary": 0.8, "marvelous": 0.8, "masterful": 0.8, "outstanding": 0.8,
    "polished": 0.7, "powerful": 0.7, "premium": 0.7, "primo": 0.8, "quality": 0.7, "rad": 0.6,
    "remarkable": 0.8, "rocking": 0.7, "sensational": 0.8, "sick": 0.7, "spectacular": 0.8,
    "splendid": 0.7, "stellar": 0.8, "striking": 0.7, "stunning": 0.8, "stylish": 0.6,
    "super": 0.6, "superb": 0.8, "superior": 0.7, "terrific": 0.8, "thrilling": 0.7,
    "top-notch": 0.8, "tremendous": 0.7, "valuable": 0.6, "vibrant": 0.7, "virtuous": 0.8,
    "A+": 1, "ace": 0.9, "astonishing": 0.9, "best": 1, "champion": 0.9, "chief": 0.9,
    "consummate": 0.9, "elite": 0.9, "epic": 0.9, "exemplary": 0.9, "exquisite": 0.9,
    "extraordinary": 0.9, "flawless": 1, "foremost": 0.9, "god-tier": 1, "greatest": 1,
    "heavenly": 0.9, "ideal": 0.9, "immaculate": 1, "impeccable": 1, "incomparable": 0.9,
    "magnificent": 0.9, "majestic": 0.9, "masterpiece": 1, "matchless": 0.9, "mind-blowing": 0.9,
    "miraculous": 0.9, "monumental": 0.9, "optimal": 0.9, "peerless": 0.9, "phenomenal": 0.9,
    "pinnacle": 1, "pristine": 0.9, "quintessential": 0.9, "second-to-none": 1, "sublime": 0.9,
    "supreme": 1, "transcendent": 0.9, "ultimate": 1, "unbeatable": 1, "unbelievable": 0.9,
    "unequaled": 0.9, "unmatched": 0.9, "unparalleled": 0.9, "unrivaled": 0.9, "unsurpassed": 0.9,
    "utopia": 1, "world-class": 0.9, "zenith": 1, "100%": 0.8, "accurate": 0.6, "agreed": 0.6,
    "amen": 0.7, "bet": 0.6, "certainly": 0.7, "correct": 0.6, "exactly": 0.7, "for sure": 0.6,
    "hell yeah": 0.8, "indeed": 0.6, "of course": 0.6, "precisely": 0.7, "right": 0.5, "true": 0.5,
    "truth": 0.6, "undoubtedly": 0.7, "unquestionably": 0.8, "valid": 0.6, "very well": 0.5,
    "yep": 0.4, "yes": 0.5, "yessir": 0.6, "amused": 0.6, "blessed": 0.8, "blissful": 0.9,
    "celebratory": 0.7, "cheerful": 0.6, "content": 0.5, "ecstatic": 0.9, "elated": 0.9,
    "euphoric": 1, "exhilarated": 0.9, "gleeful": 0.7, "grateful": 0.7, "heartwarming": 0.8,
    "hopeful": 0.6, "inspired": 0.7, "jolly": 0.6, "joy": 0.8, "joyful": 0.8, "joyous": 0.8,
    "jubilant": 0.9, "laughing": 0.7, "merry": 0.6, "optimistic": 0.6, "overjoyed": 0.9,
    "paradise": 1, "proud": 0.7, "pumped": 0.8, "rapturous": 0.9, "rejoicing": 0.8,
    "relieved": 0.6, "satisfied": 0.5, "stoked": 0.8, "thankful": 0.7, "thrilled": 0.8,
    "triumphant": 0.9, "upbeat": 0.6, "victorious": 0.9, "banger": 0.8, "based": 0.7,
    "bussin": 0.8, "chad": 0.8, "cheers": 0.5, "clutch": 0.8, "fire": 0.9, "flex": 0.6,
    "fresh": 0.6, "G.O.A.T.": 1, "goat": 1, "king": 0.9, "lit": 0.8, "pog": 0.7,
    "poggers": 0.7, "queen": 0.9, "slaps": 0.8, "slay": 0.8, "snatched": 0.7, "vibe": 0.5,
    "adore": 0.9, "angel": 0.9, "beloved": 0.9, "cherish": 0.8, "darling": 0.8, "dear": 0.7,
    "gem": 0.8, "hero": 0.9, "honey": 0.7, "precious": 0.8, "sweetheart": 0.8, "treasure": 0.9
}
NEGATIVE_WORDS = {
    "worst": -1.0, "hate": -0.9, "awful": -0.9, "horrible": -0.9, "terrible": -0.8,
    "sucks": -0.8, "dislike": -0.8, "boring": -0.7, "frustrating": -0.7, "sad": -0.7,
    "annoying": -0.6, "disappointing": -0.6, "bad": -0.6, "lame": -0.5, "bummer": -0.5,
    "rough": -0.5, "unfortunate": -0.5, "meh": -0.4, "ugh": -0.4, "awkward": -0.4,
    "bland": -0.5, "cheap": -0.4, "clumsy": -0.3, "confusing": -0.4, "corny": -0.4,
    "creepy": -0.5, "dated": -0.4, "dull": -0.5, "faulty": -0.5, "flawed": -0.4,
    "icky": -0.5, "imperfect": -0.3, "inconvenient": -0.4, "inferior": -0.5, "lacking": -0.4,
    "mediocre": -0.5, "messy": -0.4, "misguided": -0.5, "mundane": -0.5, "nope": -0.3,
    "not good": -0.5, "odd": -0.3, "old": -0.3, "overrated": -0.5, "pain": -0.5, "poor": -0.5,
    "questionable": -0.4, "stale": -0.5, "strange": -0.4, "subpar": -0.5, "tacky": -0.5,
    "tired": -0.4, "trivial": -0.3, "uninspired": -0.5, "unpleasant": -0.5, "weak": -0.4,
    "weird": -0.4, "abysmal": -0.8, "aggravating": -0.7, "alarming": -0.6, "angry": -0.7,
    "atrocious": -0.8, "brutal": -0.7, "callous": -0.8, "careless": -0.6, "chaotic": -0.7,
    "cold": -0.6, "corrupt": -0.8, "cowardly": -0.7, "criminal": -0.8, "cruel": -0.8,
    "damaging": -0.7, "dangerous": -0.8, "deceitful": -0.8, "defective": -0.7,
    "deplorable": -0.8, "disaster": -0.8, "disastrous": -0.8, "disgraceful": -0.8,
    "dishonest": -0.7, "dismal": -0.7, "distressing": -0.7, "disturbing": -0.8,
    "dreadful": -0.8, "embarrassing": -0.7, "enraging": -0.8, "evil": -0.8, "foul": -0.8,
    "garbage": -0.8, "ghastly": -0.8, "grim": -0.7, "gross": -0.7, "gruesome": -0.8,
    "harmful": -0.7, "harsh": -0.6, "hateful": -0.8, "hideous": -0.8, "hostile": -0.7,
    "idiotic": -0.8, "ignorant": -0.7, "immoral": -0.8, "infuriating": -0.8,
    "insufferable": -0.8, "insulting": -0.7, "intolerable": -0.8, "irritating": -0.6,
    "jealous": -0.6, "junky": -0.7, "laughable": -0.6, "malicious": -0.8, "monstrous": -0.8,
    "nasty": -0.7, "nauseating": -0.8, "negative": -0.6, "obnoxious": -0.7,
    "offensive": -0.8, "outrageous": -0.7, "pathetic": -0.8, "pissed": -0.8,
    "poisonous": -0.8, "predatory": -0.8, "problematic": -0.6, "repugnant": -0.8,
    "repulsive": -0.8, "revolting": -0.8, "rotten": -0.7, "rude": -0.6, "scary": -0.7,
    "severe": -0.6, "shameful": -0.7, "shocking": -0.6, "shoddy": -0.7, "sinister": -0.8,
    "stressful": -0.6, "stupid": -0.8, "toxic": -0.8, "tragic": -0.8, "trashy": -0.7,
    "unacceptable": -0.8, "unbearable": -0.8, "unethical": -0.8, "unfair": -0.7,
    "unprofessional": -0.7, "unstable": -0.7, "unwatchable": -0.8, "useless": -0.8,
    "vile": -0.8, "violent": -0.8, "worthless": -0.8, "wretched": -0.8, "abhorrent": -1,
    "abomination": -1, "amoral": -0.9, "barbaric": -0.9, "cancerous": -1, "condemned": -0.9,
    "contemptible": -0.9, "corrosive": -0.9, "damned": -0.9, "degenerate": -1, "demonic": -1,
    "despicable": -1, "detestable": -1, "disgusting": -1, "execrable": -1, "heinous": -1,
    "hellish": -1, "irredeemable": -1, "loathsome": -1, "malevolent": -0.9, "nefarious": -0.9,
    "nightmare": -0.9, "nightmarish": -0.9, "obscene": -0.9, "pernicious": -0.9,
    "perverted": -0.9, "putrid": -1, "rancid": -0.9, "sadistic": -1, "scum": -1,
    "soulless": -0.9, "unforgivable": -1, "unspeakable": -0.9, "vicious": -0.9,
    "villainous": -0.9, "abandoned": -0.8, "anguish": -0.9, "anxious": -0.6,
    "apathetic": -0.7, "bleak": -0.8, "broken": -0.8, "crushed": -0.9, "defeated": -0.7,
    "dejected": -0.8, "depressed": -0.9, "depressing": -0.9, "desolate": -0.8,
    "despair": -0.9, "desperate": -0.8, "devastated": -0.9, "drained": -0.7, "empty": -0.8,
    "grief": -0.9, "heartbreak": -0.9, "heartbroken": -0.9, "helpless": -0.8,
    "hopeless": -0.9, "hurting": -0.7, "lonely": -0.8, "lost": -0.7, "miserable": -0.9,
    "misery": -0.9, "mourning": -0.8, "numb": -0.7, "overwhelmed": -0.7, "powerless": -0.8,
    "regret": -0.7, "rejected": -0.8, "somber": -0.7, "sorrow": -0.8, "suffering": -0.9,
    "suicidal": -1, "tears": -0.7, "torment": -0.9, "torture": -0.9, "troubled": -0.6,
    "unhappy": -0.7, "weeping": -0.8, "woe": -0.8, "amateur": -0.6, "bankrupt": -0.8,
    "botched": -0.7, "catastrophe": -0.9, "debacle": -0.8, "defunct": -0.6, "error": -0.5,
    "fail": -0.8, "failure": -0.8, "fiasco": -0.8, "foolish": -0.6, "futile": -0.7,
    "illogical": -0.6, "incompetent": -0.8, "ineffective": -0.7, "inept": -0.8,
    "ruined": -0.8, "shambles": -0.7, "unskilled": -0.6, "unsuccessful": -0.7,
    "vain": -0.6, "wrong": -0.5, "basic": -0.5, "bruh": -0.4, "cancelled": -0.7,
    "cringe": -0.7, "cringey": -0.7, "facepalm": -0.5, "flop": -0.7, "ick": -0.6,
    "oof": -0.5, "simp": -0.6, "sus": -0.5, "trash": -0.8, "tryhard": -0.5, "yikes": -0.6,
    "arse": -0.7, "arsehole": -0.9, "ass": -0.7, "ass-hat": -0.9, "asshole": -1,
    "bastard": -0.9, "bitch": -1, "bitchy": -0.8, "bollocks": -0.7, "bullshit": -0.8,
    "clown": -0.8, "cock": -0.8, "cocksucker": -1, "crap": -0.6, "crappy": -0.7, "cunt": -1,
    "damn": -0.6, "dammit": -0.6, "dick": -0.9, "dickhead": -1, "douche": -0.9,
    "douchebag": -1, "dumbass": -0.9, "fag": -1, "faggot": -1, "fuck": -0.9, "fucked": -1,
    "fucker": -1, "fucking": -0.9, "fuckwit": -1, "goddamn": -0.7, "hell": -0.6,
    "incel": -0.9, "jackass": -0.9, "jerk": -0.8, "motherfucker": -1, "piss": -0.7,
    "prick": -0.9, "retard": -1, "retarded": -1, "scumbag": -1, "shit": -0.8,
    "shit-tier": -0.9, "shite": -0.8, "shithole": -1, "shitty": -0.9, "slut": -0.9,
    "son of a bitch": -1, "twat": -0.9, "wanker": -0.9, "whore": -0.9
}
AROUSAL_WORDS = {
    "!": 0.3, "!!": 0.6, "!!!": 0.8, "aaah": 0.9, "absolutely": 0.8, "alarm": 0.7, "alive": 0.6,
    "amazing": 0.8, "angry": 0.7, "anxious": 0.6, "are you kidding me": 0.8, "are you serious": 0.8,
    "attack": 0.7, "boom": 0.7, "crazy": 0.8, "crisis": 0.8, "danger": 0.8, "ecstatic": 0.9,
    "emergency": 0.9, "enraged": 0.9, "epic": 0.8, "euphoric": 0.9, "excited": 0.7, "explosion": 0.9,
    "fast": 0.6, "fear": 0.7, "fight": 0.7, "fuck": 0.9, "fuck yeah": 1, "furious": 0.9,
    "get out": 0.7, "go": 0.6, "help": 0.8, "holy shit": 0.9, "hurry": 0.7, "hype": 0.8,
    "hyped": 0.8, "incredible": 0.8, "insane": 0.9, "intense": 0.7, "jesus christ": 0.8,
    "let's go": 0.8, "mad": 0.7, "mind-blowing": 0.9, "no fucking way": 1, "no way": 0.7,
    "now": 0.6, "omfg": 0.9, "omg": 0.7, "panic": 0.8, "pumped": 0.8, "quick": 0.6, "rage": 0.9,
    "riot": 0.8, "run": 0.7, "scream": 0.8, "shit": 0.7, "shock": 0.7, "shocked": 0.7,
    "stop": 0.6, "stoked": 0.8, "surprise": 0.6, "terrified": 0.9, "thrill": 0.7,
    "unbelievable": 0.8, "urgent": 0.8, "violence": 0.8, "wait": 0.5, "watch out": 0.8,
    "what the fuck": 1, "what?!": 0.8, "whoa": 0.6, "wild": 0.7, "wtf": 0.9, "yell": 0.7,
    "yes!": 0.7, "what": 0.5, "wow": 0.6, "apathetic": -0.8, "asleep": -1, "blah": -0.7,
    "bored": -0.7, "boring": -0.7, "calm": -0.5, "chill": -0.4, "dead": -0.9, "depleted": -0.7,
    "drained": -0.8, "drowsy": -0.6, "dull": -0.6, "exhausted": -0.8, "fatigued": -0.7,
    "flat": -0.6, "indifferent": -0.8, "lazy": -0.6, "lethargic": -0.9, "lifeless": -0.9,
    "low": -0.5, "meh": -0.6, "mild": -0.4, "numb": -0.8, "passive": -0.6, "peaceful": -0.7,
    "quiet": -0.5, "relaxed": -0.6, "serene": -0.8, "sleepy": -0.4, "slow": -0.5,
    "sluggish": -0.7, "still": -0.6, "subtle": -0.4, "tired": -0.6, "tranquil": -0.8,
    "uninterested": -0.7, "weary": -0.7, "whatever": -0.7, "zonked": -0.8, "aha": 0.3,
    "bahaha": 0.5, "giggle": 0.3, "haha": 0.2, "hahaha": 0.4, "hehe": 0.2, "hilarious": 0.6,
    "i'm dead": 0.6, "i'm dying": 0.6, "kek": 0.4, "lmfao": 0.7, "lmao": 0.5, "lol": 0.3,
    "lolz": 0.3, "pmsl": 0.7, "rofl": 0.6, "roflmao": 0.7, "?": 0.2, "?!": 0.6, "??": 0.4,
    "???": 0.6, "...": -0.2, "hmm": -0.1, "huh": 0.3, "oh": 0.2, "uh": -0.1, "um": -0.1, "well": -0.1
}
INTENSIFIERS = {"very": 1.5, "so": 1.4, "really": 1.4, "extremely": 1.7, "incredibly": 1.7, "super": 1.6, "insanely": 1.8}
NEGATION_WORDS = {"not", "no", "never", "don't", "can't", "won't", "isn't", "aren't", "wasn't", "weren't"}

# Semantic Intent & Categorization
VULNERABLE_WORDS = [
    "a little scared", "confess", "feeling a bit down", "i admit", "i struggle with",
    "i've never told anyone", "i'm worried", "is that weird", "it's been tough",
    "my secret is", "nervous", "opening up", "i have a confession", "i must admit",
    "i have to confess", "my biggest fear is", "my weakness is", "the truth is",
    "can i tell you a secret?", "full disclosure", "i shouldn't say this but",
    "i messed up", "it was my fault", "i regret", "i was wrong", "i apologize for",
    "for what it's worth", "it makes me feel", "deep down", "on the inside",
    "my heart sank", "i'm hurting", "i feel so alone", "i'm lost", "i'm not okay",
    "i feel empty", "it hurts", "this is hard for me to say", "i'm going through a lot",
    "i'm at my limit", "i can't handle this", "am i crazy for", "call me crazy but",
    "does that make any sense?", "don't judge me but", "is it just me or",
    "i might be wrong but", "maybe i'm overthinking this", "tell me what you think",
    "what should i do?", "you probably think i'm", "i need your advice",
    "am i being unreasonable?", "is this normal?", "i feel insecure about",
    "i'm not good enough", "i'm trying my best", "i'm scared of", "i'm afraid",
    "i feel like a failure", "i'm struggling with", "my anxiety is", "i'm so anxious",
    "i'm overwhelmed", "i don't know how to", "i'm not sure if", "i doubt", "i worry that"
]
SEXUAL_WORDS = [
    "craving", "cuddle", "desire", "hot", "kiss", "lips", "make a move", "naughty",
    "pleasure", "sexy", "taste", "tease", "touch", "undress", "adore", "all night",
    "caress", "cherish", "embrace", "erotic", "explore", "foreplay", "hold me",
    "intimacy", "intimate", "lover", "making love", "massage", "naked", "passion",
    "passionate", "ravish", "romance", "seduce", "seductive", "sensual", "share a bed",
    "slowly", "tender", "whisper", "alone time", "can't wait",
    "can't stop thinking about you", "come here", "get you alone", "i want you",
    "in the mood", "let's get into trouble", "let's play", "make you mine", "mischief",
    "need you", "private", "room for two", "temptation", "tempting", "turn on",
    "turned on", "what are you wearing", "you drive me crazy", "you turn me on", "abs",
    "anus", "areola", "ass", "asshole", "balls", "bellend", "boobies", "boobs", "breast",
    "breasts", "butt", "butt-hole", "cheeks", "chest", "clit", "clitoris", "cock",
    "crotch", "dick", "erection", "g-spot", "genitals", "glutes", "groin", "hole",
    "member", "nipple", "nipples", "nuts", "package", "pecker", "penis", "prostate",
    "pussy", "scrotum", "shaft", "taint", "testicles", "thighs", "tits", "titties",
    "tongue", "vagina", "bang", "beat", "bend over", "blow", "blowjob", "bone", "bukkake",
    "choke", "come", "creampie", "cunnilingus", "deepthroat", "devour", "doggy style",
    "dominate", "drill", "eat out", "ejaculate", "face-sit", "facial", "fellatio",
    "finger", "fingering", "fist", "fisting", "fuck", "fucking", "gangbang", "go down on",
    "grind", "handjob", "have sex", "head", "hump", "inside you", "jack off", "jerk off",
    "jizz", "lick", "mount", "nail", "orgasm", "pegging", "penetrate", "penetration",
    "pound", "pump", "rail", "rim", "rimjob", "ride", "rub", "satisfy", "screw", "shag",
    "sixty-nine", "smash", "spitroast", "spread", "stroke", "suck", "suck off", "submit",
    "swallow", "take it", "thrust", "top", "toss off", "wank", "aroused", "climax",
    "creamy", "cum", "cumshot", "dripping", "erect", "hard", "horny", "in heat",
    "juices", "lust", "moist", "precum", "randy", "rock-hard", "seed", "semen", "slutty",
    "sperm", "stiff", "throbbing", "wet", "aftercare", "age play", "ball gag", "bdsm",
    "blindfold", "bondage", "brat", "breath play", "cane", "chain", "chastity", "collar",
    "daddy", "ddlg", "discipline", "dom", "dominant", "domme", "dungeon", "edge", "edging",
    "femboy", "femdom", "fetish", "flog", "gag", "handcuffs", "harness", "humiliation",
    "impact play", "kink", "kinky", "leash", "leather", "latex", "little", "master",
    "mistress", "mommy", "owner", "paddle", "pet", "pet play", "punish", "punishment",
    "rope", "rough", "safeword", "sadism", "serve", "service", "slave", "spank",
    "spanking", "sub", "submission", "submissive", "switch", "tame", "tie me up",
    "use me", "whip", "anal beads", "ben wa balls", "bondage tape", "butt plug", "cock ring",
    "condom", "dildo", "fleshlight", "g-spot vibrator", "hitachi", "lingerie", "lube",
    "nipple clamps", "paddles", "restraints", "riding crop", "sex swing", "sex toy",
    "strapon", "vibrator", "affair", "all fours", "backseat", "bedroom", "counter",
    "hookup", "hotel", "motel", "one night stand", "orgy", "porn", "pornography", "sex",
    "sexual", "shower", "threesome"
]
PLANNING_WORDS = [
    "get", "grab", "meet", "hang out", "do", "go", "have", "catch", "make", "take", "share", "join",
    "come by", "come over", "come through", "drop by", "stop by", "swing by", "head to", "head over",
    "roll through", "pop in", "show up", "make it", "get to", "arrive", "be at", "get together", "link up",
    "meet up", "catch up", "kick it", "chill", "vibe", "connect", "hit up", "hit", "scoop", "slide",
    "post up", "arrange", "schedule", "organize", "coordinate", "convene", "assemble", "attend", "gather",
    "fuck with", "mess with", "drink", "drinks", "coffee", "dinner", "lunch", "brunch", "breakfast",
    "food", "a meal", "a bite", "something to eat", "tea", "a beer", "beers", "cocktails", "a round",
    "apps", "a movie", "the movies", "a game", "the game", "a show", "a concert", "a party", "the party",
    "the event", "the function", "the move", "the spot", "a walk", "a hike", "a workout", "sometime",
    "soon", "later", "some point", "at some point", "one day", "one of these days", "in a bit",
    "in the future", "eventually", "down the road", "whenever", "weekend", "the weekend", "this weekend",
    "next weekend", "friday", "saturday", "sunday", "monday", "tuesday", "wednesday", "thursday", "fri",
    "sat", "sun", "mon", "tues", "weds", "thurs", "tonight", "tn", "tomorrow", "tmrw", "today",
    "the morning", "morning", "am", "the afternoon", "afternoon", "pm", "the evening", "evening",
    "night", "the night", "this week", "next week", "the week", "a weekday", "this month", "next month",
    "the holiday", "the break", "later on", "in an hour", "my place", "your place", "my spot", "your spot",
    "mine", "yours", "the bar", "the cafe", "the restaurant", "the club", "downtown", "town"
]
GEO_TRIGGERS = {
    "where", "from", "at", "in", "on", "near", "by", "around", "to", "live", "lives", "living", "reside",
    "resides", "residence", "home", "hometown", "homeland", "based", "staying", "grew up", "born in",
    "raised in", "native", "local", "nationality", "citizenship", "roots", "background", "travel",
    "traveling", "traveled", "visit", "visiting", "trip", "vacation", "holiday", "journey", "tour",
    "expedition", "voyage", "pilgrimage", "excursion", "getaway", "go", "went", "going", "fly", "flew",
    "flying", "drive", "drove", "driving", "commute", "commuting", "relocate", "relocating", "move",
    "moved", "moving", "emigrate", "immigrate", "abroad", "overseas", "destination", "itinerary", "route",
    "path", "country", "nation", "state", "province", "county", "city", "town", "village", "municipality",
    "district", "territory", "capital", "border", "continent", "region", "area", "zone", "hemisphere",
    "coast", "island", "peninsula", "mountain", "valley", "desert", "forest", "jungle", "ocean", "sea",
    "river", "lake", "located", "location", "place", "spot", "venue", "site", "address", "building",
    "office", "campus", "headquarters", "hq", "airport", "station", "port", "hotel", "resort", "park",
    "neighborhood", "suburb", "north", "south", "east", "west", "northern", "southern", "eastern",
    "western", "upstate", "downstate", "uptown", "downtown", "midtown", "central", "remote", "nearby",
    "distant", "here", "there", "everywhere", "somewhere", "anywhere", "nowhere", "position",
    "coordinates", "latitude", "longitude", "lat", "long", "gps", "map", "atlas", "globe", "directions",
    "geography", "geolocation", "geotag", "geofence", "locale", "jurisdiction", "branch", "outlet",
    "market", "shipping", "delivery", "origin", "street", "road", "avenue", "boulevard", "lane",
    "drive", "court", "zip code", "postal code", "postcode", "p.o. box", "hood", "neck of the woods",
    "stomping grounds", "turf", "ends", "area code", "the sticks", "the burbs", "back home"
}
PROFESSIONAL_WORDS = {
    "work", "job", "career", "office", "company", "project", "meeting", "business",
    "industry", "role", "profession", "colleague"
}

# Behavioral Patterns
LOW_EFFORT_WORDS = {
    "ok", "okay", "oki", "okie", "k", "kk", "kay", "yep", "yup", "yuppers", "yeah", "ya", "yah",
    "aight", "alright", "alrighty", "gotcha", "got it", "i see", "isee", "ah", "aha", "understood",
    "word", "lol", "lolz", "haha", "hehe", "ha", "he", "cool", "nice", "sweet", "dope", "sick",
    "lit", "cute", "love it", "amazing", "awesome", "thx", "thanks", "ty", "tysm", "np", "yw",
    "idk", "idek", "ofc", "atm", "rn", "fr", "hbu", "wbu", "wyd", "nm", "gn", "gm", "gl", "gg",
    "lmao", "lmfao", "rofl", "👍", "👌", "😂", "❤️", "🔥", "💯", "🙏", "🤣", "😁", "😊", "😉",
    "💀", "🙂", "✅", "✔️", "noted", "copy", "copy that", "roger", "roger that", "received",
    "acknowledged", "will do", "sounds good", "sg", "sgtm", "perfect", "done", "hmm", "hm",
    "huh", "oh", "well", "fair", "fair enough", "true", "valid", "i guess", "i suppose",
    "maybe", "perhaps", "possibly", "...", "k.", "fine.", "fine", "whatever", "w/e", "sure.",
    "sure", "idc", "cool.", "nice.", "wow.", "lol.", "."
}
GREETING_KEYWORDS = {
    "afternoon", "evening", "g'day", "good afternoon", "good day", "good evening", "good morning",
    "greetings", "hello", "heya", "hey", "hi", "hiya", "how's it going", "howdy", "morning",
    "sup", "wassup", "what's good", "what's up", "what up", "yo"
}
INDIRECT_QUESTION_STARTERS = ["i was wondering", "i'm curious", "tell me about", "what do you think about"]
POWER_MOVE_PHRASES = ["i'll let you know", "we'll see", "let me get back to you", "i'm busy"]
SHIT_TEST_PATTERNS = [
    r"i bet you say that to all",
    r"are you a player\b",
    r"you probably have so many",
    r"don't break my heart",
    r"are you trying to",
    r"you must be",
    r"\bslow down\b",
    r"\bgetting to know you\b",
    r"\bfar away\b",
    r"in the next few weeks",
    r"prove it\b",
    r"impress me\b",
    r"are you always this",
    r"you seem like trouble",
]

# Emojis & Misc
SEXUAL_EMOJIS = re.compile(r"[😏😈🔥💦🥵😜😉💋👅🍑🍆🛏️🤤😇👀💅✨🫦👉👌👇👆💨♋️69💥💫🌶️🍭🍦🍩🌮🌭🍌🍒🍾🥂⛓️🔗🪢🪚🔨📍📌️🕯️🔑🔐🍼]")
AMBIGUOUS_PHRASES = ["im down", "sounds good", "maybe", "we should", "sometime"]
SARCASTIC_MARKERS = ["yeah right", "sure...", "whatever", "obviously"]